services:
  chatgpt:
    image: gpt4:latest
    container_name: gpt4
    environment:
      - ROOT_LOG_LEVEL=INFO
      - APP_LOG_LEVEL=DEBUG
    env_file:
      - .env
    networks:
      - chatgpt
    ports:
      - 10.8.0.3:9191:9191
    restart: unless-stopped

networks:
  chatgpt:
