version: '3.8'
services:
  db:
    image: postgres:12-alpine
    restart: always
    container_name: pg
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - '0.0.0.0:5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
volumes:
  db: