#!/bin/bash
source /home/ubuntu/gpt4/venv/bin/activate
source /home/ubuntu/gpt4/.env
export ENV=PROD
export SUBDIRECTORY=gpt4
export DOMAIN=sebampuerom.de
export OPENAI_KEY=$OPENAPI_APIKEY
export CLIENT_ID=$CLIENT_ID
export CLIENT_SECRET=$CLIENT_SECRET
export JWT_SECRET=$JWT_SECRET
export PROJECT_ID=$PROJECT_ID
export MISTRAL_API_KEY=$MISTRAL_API_KEY
export CLAUDE_MODEL=claude-3-5-sonnet-20240620
export CLAUDE_KEY=$CLAUDE_KEY
export DDB_CHATS_TABLE=chats
export DDB_USERS_TABLE=authorized_users
export GPT_MODEL=gpt-4o-2024-05-13
export GEMINI_MODEL=gemini-1.5-pro-001
export MISTRAL_MODEL=mistral-large-latest
export ES_HOST=192.168.0.7
export ES_PORT=9200
python3 /home/ubuntu/gpt4/server.py
