import React, { useState, useEffect, useRef  } from 'react';
import ChatSidebar from './ChatSidebar';
import './ChatPage.css';
import Cookies from 'js-cookie';

const ChatPage = ({ email }) => { //TODO: this component could be separated in more other components (messageinput, options dialog, etc)
  const [messageInput, setMessageInput] = useState('');
  const [optionsVisible, setOptionsVisible] = useState(false);
  const [chatMessages, setChatMessages] = useState([]);
  const [chats, setChats] = useState([]);
  const [socket, setSocket] = useState(null);
  const [sidebarVisible, setSidebarVisible] = useState(false);
  const [isPromptLoading, setIsPromptLoading] = useState(false);
  const [selectedModel, setSelectedModel] = useState("Gemini");

  const currentSocketId = useRef("");
  const currentChatId = useRef("");
  const currentChatTimestamp = useRef(0);
  const imageDataURL = useRef(null);
  const imgBase64Data = useRef("");

  const MAX_IMG_WIDTH = 450;
  const MAX_IMG_HEIGHT = 450;

  const loadChats = () => {
    const token = Cookies.get('jwt');
    fetch(process.env.PUBLIC_URL + "/user/" + email, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        "Authorization": token
      }
    })
      .then((response) => { 
        if(response.status === 200) return response.json();
        throw new Error(response.status)
      })
      .then((resp) => {
        const chats = resp.body
        chats.sort((a, b) => b.timestamp - a.timestamp);
        chats.forEach(obj => {
          let userContent = obj.messages.find(msg => msg.role === 'user')?.content;
          obj.title = userContent.substring(0,25) + "..."; // very basic and naive way to show main idea of a chat
        })
        setChats(chats)
      })
      .catch((error) => {
        console.error("Error:", error);
        if (error.message === "401") alert("Please reload the page and log in again")
        else if (error.message === "400") alert("There was a problem loading your chats!")
        else alert("There was an error, please try again later")
      });
  }

  const createSocket = () => {
    if(!socket){
      const token = Cookies.get('jwt');
      const socketUrl = process.env.NODE_ENV === 'production'
      ? process.env.REACT_APP_PROD_WS_URL
      : process.env.REACT_APP_WS_URL;
      const socket = new WebSocket(`${socketUrl}?token=${token}`);

      socket.addEventListener('open', () => {
        console.log('WebSocket connection opened');      
      });

      socket.addEventListener('message', (event) => {
        processMessageType(event.data)
      });

      socket.addEventListener('error', (event) => {
        console.error('WebSocket error:', event);
        alert("There was an error, try again later.");
      });

      socket.addEventListener('close', (event) => {
        console.log('WebSocket connection closed:', event);
      });

      setSocket(socket);
    }
  }

  const closeSocket = () => {
    if (socket) {
      socket.close()
      setSocket(null)
    }
  }

  useEffect(() => {
    loadChats()
    const model = Cookies.get('model')
    if (model) {
      setSelectedModel(model)
    }
    if (!socket){
      createSocket()
    }
  }, [socket]); // needed here because rendering is needed every time a new chat is selected

  const displayMessage = (messageContent, messageType) => {
    const newMessage = {
      timestamp: Date.now(), 
      content: messageContent,
      role: messageType,
      image: imageDataURL.current
    };
    setChatMessages((prevMessages) => [...prevMessages, newMessage]);
  };
  const retrieveMessagesForNewOpenedChat = (newSocketId) => {
    const token = Cookies.get('jwt');
    fetch(process.env.PUBLIC_URL + `/chat/${currentChatId.current}/${currentChatTimestamp.current}/${newSocketId}/${currentSocketId.current}`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        "Authorization": token
      }
    })
      .then((response) => { 
        if (response.status === 200) return response.json();
        else throw new Error(response.status)
      })
      .then((resp) => {
        const chat = resp.body
        setChatMessages(() => {
          chat.messages.forEach(obj => {
            if(obj.image) obj.image = `data:image/jpg;base64,${obj.image}`
          })
          return chat.messages
        })
      })
      .catch((error) => {
        console.error("Error: ", error);
        if (error.message === "401") alert("Please reload the page and log back in")
        else if (error.message === "404") alert("Could not find Chat")
        else alert("There was an error, please try again later")
      });
  }
  const processMessageType = (data) => {
    const msg = JSON.parse(data);
    if (msg.type === "INIT"){
      sendNewModel(selectedModel, msg.socket_id)
      if(currentChatId.current != "") { // socket id is generated by the backend
        retrieveMessagesForNewOpenedChat(msg.socket_id)
      }
      currentSocketId.current = msg.socket_id
    }else if(msg.type === "CONTENT"){
      handleReceivedMessage(data)
    }
  }

  const handleReceivedMessage = (message) => {
    const messageObj = JSON.parse(message)
    if (messageObj.content === "END") {
      setIsPromptLoading(false);
      imgBase64Data.current = "";
      imageDataURL.current = null;
      //TODO: add option to format message when gpt sends code surrounded by `code`
      return
    }
    setChatMessages((prevMessages) => {
      const existingMessageIndex = prevMessages.findIndex((msg) => msg.timestamp === messageObj.timestamp);
      if (existingMessageIndex !== -1) {
        const updatedMessages = [...prevMessages];
        updatedMessages[existingMessageIndex].content += messageObj.content;
        return updatedMessages;
      } else {
        const newMessage = {
          timestamp: messageObj.timestamp,
          content: messageObj.content,
          role: 'peer',
        };
        return [...prevMessages, newMessage];
      }
    });
  };

  const resizeImageAndConvertToBase64 = (binaryData, maxWidth, maxHeight) => {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.src = URL.createObjectURL(new Blob([new Uint8Array(binaryData)]));
      img.onload = function () {
        const canvas = document.createElement("canvas");
        const ctx = canvas.getContext("2d");

        let width = img.width;
        let height = img.height;

        if (width > maxWidth) {
          height *= maxWidth / width;
          width = maxWidth;
        }

        if (height > maxHeight) {
          width *= maxHeight / height;
          height = maxHeight;
        }

        canvas.width = width;
        canvas.height = height;

        ctx.drawImage(img, 0, 0, width, height);

        canvas.toBlob(blob => {
          imageDataURL.current = URL.createObjectURL(blob);
          const reader = new FileReader();
          reader.onload = function () {
            resolve(reader.result.split(',')[1]);
          };

          reader.readAsDataURL(blob);
        }, 'image/jpeg');
      };

      img.onerror = reject;
    });
  }
  const handleImageUpload = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = function (e) {
        resizeImageAndConvertToBase64(e.target.result, MAX_IMG_WIDTH, MAX_IMG_HEIGHT)
        .then(base64Data => {
          alert("Image loaded!")
          imgBase64Data.current = base64Data;
        })
        .catch(error => {
          console.error('Error:', error);
          alert("There was an error uploading the image");
          imgBase64Data.current = "";
          imageDataURL.current = null;
        });
      };
      reader.readAsArrayBuffer(file);
    }
  };

  const sendMessage = () => {
    if (messageInput.trim() === '') return
    if (socket && socket.readyState === WebSocket.OPEN) {
      const message = {
        msg: messageInput,
        email: email,
        chat_id: currentChatId.current,
        image: imgBase64Data.current
      };
      socket.send(JSON.stringify(message));
      setMessageInput('');
    }else{
      alert("The connection to the server is closed, please reload the page.")
    }
    displayMessage(messageInput, 'user');
    setIsPromptLoading(true);
  };

  const showOptions = () => {
    setOptionsVisible(!optionsVisible);
  }

  const switchChat = (chatId, timestamp) => {
    console.log("Switching chat to " + chatId)
    currentChatId.current = chatId;
    currentChatTimestamp.current = timestamp;
    closeSocket();
    createSocket();
    setSidebarVisible(false);
    setOptionsVisible(false);
  };

  const newChat = () => {
    setChatMessages([]);
    currentChatId.current = "";
    imgBase64Data.current = "";
    imageDataURL.current = null;
    closeSocket();
    createSocket();
    setSidebarVisible(false);
    setOptionsVisible(false);
  }

  const toggleSidebar = () => {
    setSidebarVisible(!sidebarVisible);
  };

  const deleteChat = (chatId, timestamp) => {
    const token = Cookies.get('jwt');
    fetch(process.env.PUBLIC_URL + `/chat/${chatId}/${timestamp}`, {
      method: "DELETE",
      headers: {
        "Authorization": token
      }
    })
      .then((response) => { 
        if(response.status === 204) setChats((prevChats) => prevChats.filter((chat) => chat.chat_id !== chatId));
        else throw new Error("Could not delete chat with ID " + chatId)
      })
      .catch((error) => {
        console.error("Error:", error);
        alert("There was a problem deleting the chat.")
      });
  };

  const sendNewModel = (model, socket_id) => {
    const token = Cookies.get('jwt');
    fetch(process.env.PUBLIC_URL + `/model/${socket_id}`, {
      method: "POST",
      headers: {
        "Authorization": token
      },
      body: JSON.stringify({"model": model})
    })
    .catch((error) => {
      console.error("Error:", error);
      alert("There was a problem setting the model, please try again.")
    });
  }

  const selectModel = (model) => {
    setSelectedModel(model);
    Cookies.set('model', model);
    sendNewModel(model, currentSocketId.current);
  };

  return (
    <div id="chat-container" style={{ display: 'flex' }}>
      {sidebarVisible && (
        <ChatSidebar chats={chats} onChatClick={switchChat} onDeleteChat={deleteChat} />
      )}
      <div id="content-container" style={{ flex: 1 }}>
        <div id="chat-messages">
        {chatMessages.map((message) => (
            <div key={message.timestamp} className={`message-bubble ${message.role === 'user' ? 'user-message' : 'peer-message'}`}>
              {message.image && message.image !== null && (
                <img src={message.image} alt="GPT4-V image prompt" />
              )}
              <span>{message.content}</span>
            </div>
          ))}
        </div>
      </div>
      <div id="chat-input">
        <textarea
          id="message-input"
          rows="1"
          style={{ resize: 'none' }}
          value={messageInput}
          onChange={(e) => setMessageInput(e.target.value)}
          onFocus={() => setSidebarVisible(false)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault();
              sendMessage(); 
            }
          }}
        ></textarea>
        <button id="send-button" onClick={sendMessage} disabled={isPromptLoading}>
          {isPromptLoading ? (
            <i className="fa fa-spinner fa-spin"></i>
          ) : (
            <i className="fa fa-arrow-right"></i>
          )}
        </button>
        <button id="reset-button" onClick={showOptions}>
          <i className="fas fa-bars"></i>
        </button>
      </div>

      <div id="options-container" className={optionsVisible ? 'show' : 'hidden'}>
        <div id="options-header">Options</div>
        <div>
          <button id="toggle-sidebar-button" className="custom-file-upload" onClick={toggleSidebar}>
            {sidebarVisible ? 'Hide chats' : 'Show chats'}
          </button>
        </div>
        <div>
          <button id="new-chat-button" className="custom-file-upload" onClick={newChat}>
            New chat
          </button>
        </div>
        <div id="image-upload-container">
          <input
            type="file"
            id="image-input"
            accept="image/*"
            onChange={(e) => handleImageUpload(e)}
          />
          <label htmlFor="image-input" className="custom-file-upload">
            Upload Image
          </label>
        </div>
        <div>
          <button
            id="gemini-button"
            className={`custom-file-upload ${selectedModel === 'Gemini' ? 'selected' : ''}`}
            onClick={() => selectModel('Gemini')}
          >
            Gemini
          </button>
        </div>
        <div>
          <button
            id="gpt4-button"
            className={`custom-file-upload ${selectedModel === 'GPT4' ? 'selected' : ''}`}
            onClick={() => selectModel('GPT4')}
          >
            GPT4
          </button>
        </div>
      </div>
    </div>
  );
};

export default ChatPage;